version: '3.9'

services:
  chat-backend:
    image: chat-backend:latest
    container_name: chat-backend
    ports:
      - "8080:8080"
    environment:
      DB_DSN: postgresql://postgres:Pass@word@postgresql:5432/postgres?sslmode=disable
      PORT: 8080

networks:
  default:
    name: chat-backend-network